### ISSUE TITLE
Failed time.test on MacOS and Linux

### ISSUE THREAD

**Issue by LaansDole** [miketvo/rmit2022c-eeet2482-lodging-app#13]
<img width="1440" alt="Screen Shot 2023-01-03 at 3 44 26 pm" src="https://user-images.githubusercontent.com/85084360/210324403-02a91b9c-2548-4c9d-bf04-fe7fa5d515d5.png">

<img width="1440" alt="Screen Shot 2023-01-03 at 3 44 35 pm" src="https://user-images.githubusercontent.com/85084360/210324329-b7b38dcd-afbd-4f51-bed2-90cd4075d246.png">
<img width="1440" alt="Screen Shot 2023-01-03 at 3 44 31 pm" src="https://user-images.githubusercontent.com/85084360/210324346-1fad9358-86b7-4122-b450-eb1def08c3d8.png">

**Comment by miketvo** [comment]
Also the same situation on Linux, I think this is a Unix thing:
![image](https://user-images.githubusercontent.com/73817896/211042837-3ef775db-b004-4c08-a7d2-34fa5959e8e2.png)
